---
name: CI
"on":
  push:
    branches: [lintners]
  pull_request:
    branches: [master]
jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14.7
      - uses: arduino/setup-protoc@master
      - name: Build and test
        run: make
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31
